version: '3.1'
services:
  stats-server:
    build: stats/server
    container_name: stats-server
    depends_on:
      - stats-db
    environment:
      - DB_HOST=stats-db
      - DB_PORT=5432
      - DB_NAME=hit
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "9090:9090"

  stats-db:
    container_name: stats-db
    environment:
      - POSTGRES_DB=hit
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    image: postgres:14-alpine
    ports:
      - "6543:5432"

  ewm-service:
    build: ewm
    container_name: ewm-service
    depends_on:
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - DB_NAME=ewm
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "8080:8080"

  ewm-db:
    container_name: ewm-db
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    image: postgres:14-alpine
    ports:
      - "6542:5432"
