CREATE TABLE IF NOT EXISTS endpoint_hit (
    PRIMARY KEY (id),
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(255)                            NOT NULL,
    uri       VARCHAR(2048)                           NOT NULL,
    ip        VARCHAR(255)                            NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL
);